{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newsletter.secretName" . }}
  labels:
    {{- include "newsletter.labels" . | nindent 4 }}
type: Opaque
stringData:
  POCKETBASE_SUPERUSER_EMAIL: {{ .Values.credentials.superuserEmail | quote }}
  POCKETBASE_SUPERUSER_PASSWORD: {{ .Values.credentials.superuserPassword | quote }}
  POCKETBASE_ADMIN_EMAIL: {{ .Values.credentials.adminEmail | quote }}
  POCKETBASE_ADMIN_PASSWORD: {{ .Values.credentials.adminPassword | quote }}
{{- end }}
