apiVersion: v1
kind: Service
metadata:
  name: {{ include "newsletter.fullname" . }}
  labels:
    {{- include "newsletter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "newsletter.selectorLabels" . | nindent 4 }}
  ports:
    - name: frontend
      protocol: TCP
      port: {{ .Values.service.ports.frontend }}
      targetPort: frontend
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.frontend }}
      nodePort: {{ .Values.service.nodePorts.frontend }}
      {{- end }}
    - name: pocketbase
      protocol: TCP
      port: {{ .Values.service.ports.pocketbase }}
      targetPort: pocketbase
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.pocketbase }}
      nodePort: {{ .Values.service.nodePorts.pocketbase }}
      {{- end }}
