// Decode an existing embedded cover into a disposable binary read cache.
// Both paths are generated by the authenticated PocketBase route.
import { readFile, writeFile, rename, readdir, stat, unlink } from 'node:fs/promises';
import { dirname, join } from 'node:path';
const [input, output] = process.argv.slice(2);
if (!input || !output || dirname(input) !== dirname(output)) throw new Error('Invalid cover cache paths');
const bytes = Buffer.from(await readFile(input, 'utf8'), 'base64');
const temporary = output + '.' + process.pid + '.tmp';
await writeFile(temporary, bytes, { mode: 0o600 });
await rename(temporary, output);
// Bound disposable cache growth; current versions are re-created on demand.
const directory = dirname(output);
const files = (await readdir(directory)).filter((name) => /^[a-f0-9]{64}$/.test(name));
if (files.length > 128) {
  const entries = await Promise.all(files.map(async (name) => ({ name, time: (await stat(join(directory, name)).catch(() => ({ mtimeMs: 0 }))).mtimeMs })));
  entries.sort((a, b) => b.time - a.time);
  await Promise.all(entries.slice(128).filter((item) => join(directory, item.name) !== output).map((item) => unlink(join(directory, item.name)).catch(() => {})));
}
