import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { cp, mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import PocketBase from 'pocketbase';
import { APP_COLLECTION_SCHEMAS } from '../../scripts/pocketbase/app-schema.mjs';

const binary = path.resolve(process.env.NOTIFICATION_TEST_PB_BINARY || '.tmp/community-pb/pocketbase.exe');
await mkdir('.tmp', { recursive: true });
const directory = await mkdtemp(path.resolve('.tmp/notifications-test-'));
await cp('pb_hooks', path.join(directory, 'pb_hooks'), { recursive: true });
await cp('tests/fixtures/notifications-test.pb.js', path.join(directory, 'pb_hooks/notifications-test.pb.js'));
const args = [`--dir=${path.join(directory, 'pb_data')}`, `--hooksDir=${path.join(directory, 'pb_hooks')}`, `--migrationsDir=${path.join(directory, 'pb_migrations')}`];
const email = 'community-test@example.com', password = 'test-only-password-12345';
const init = spawnSync(binary, ['superuser', 'upsert', email, password, ...args], { encoding: 'utf8' });
if (init.status !== 0) throw new Error(init.stderr || 'PocketBase binary unavailable. Set NOTIFICATION_TEST_PB_BINARY.');
const port = Number(process.env.NOTIFICATION_TEST_PORT || 7092);
const server = spawn(binary, ['serve', `--http=127.0.0.1:${port}`, ...args], { stdio: ['ignore', 'pipe', 'pipe'], env: { ...process.env, APP_ROOT: process.cwd(), NODE_BINARY: process.execPath } });
let logs = '';
server.stdout.on('data', (chunk) => { logs += chunk; });
server.stderr.on('data', (chunk) => { logs += chunk; });
const url = `http://127.0.0.1:${port}`;
const root = new PocketBase(url); root.autoCancellation(false);
const send = (client, route, body, method = 'POST') => client.send(route, { method, body, requestKey: null });
const get = (client, route) => client.send(route, { requestKey: null });
const prefs = (client, body) => send(client, '/api/notifications/preferences', body, 'PATCH');
const notes = (client, kind) => get(client, '/api/community/notifications' + (kind ? `?kind=${kind}` : ''));
const tick = (now) => send(root, '/api/test/notifications/tick', { now });
const post = (client, body, extra = {}) => send(client, '/api/community/posts', { body, ...extra });
try {
  for (let i = 0; i < 100; i++) {
    try { await root.health.check(); break; } catch { await new Promise((resolve) => setTimeout(resolve, 100)); }
  }
  await root.collection('_superusers').authWithPassword(email, password);
  for (const schema of APP_COLLECTION_SCHEMAS) await root.collections.create(schema);
  const userSchema = await root.collections.getOne('users');
  await root.collections.update(userSchema.id, { fields: [...userSchema.fields, { name: 'name', type: 'text' }, { name: 'role', type: 'text' }] });
  const clients = [];
  for (const name of ['alice', 'bob', 'carol', 'dave']) {
    const account = await root.collection('users').create({ email: `${name}@example.com`, password, passwordConfirm: password, verified: true, name, role: 'viewer' });
    const client = new PocketBase(url); client.autoCancellation(false);
    await client.collection('users').authWithPassword(`${name}@example.com`, password);
    await send(client, '/api/community/me', { handle: name, displayName: name }, 'PATCH');
    clients.push({ client, id: account.id, name });
  }
  const [a, b, c, d] = clients;
  const anonymous = new PocketBase(url);
  for (const route of ['/api/notifications/preferences', '/api/notifications/unread', '/api/community/notifications']) await assert.rejects(get(anonymous, route), (error) => error.status === 401);
  await assert.rejects(prefs(a.client, { mentions: 'false' }), (error) => error.status === 400);
  await assert.rejects(prefs(a.client, { userId: b.id }), (error) => error.status === 400);
  assert.deepEqual(await get(a.client, '/api/notifications/preferences'), { enabled: true, mentions: true, comments: true, following: true, events: true, newsletters: true, activity: true, browser: true, background: true });
  await prefs(a.client, { mentions: false, enabled: false });
  assert.equal((await prefs(a.client, { enabled: true })).mentions, false, 'master switch preserves type choices');
  assert.equal((await get(b.client, '/api/notifications/preferences')).mentions, true, 'settings belong to the authenticated user');
  await post(b.client, 'Hello @alice');
  assert.equal((await notes(a.client, 'mention')).items.length, 0);
  await prefs(a.client, { mentions: true });
  const mention = await post(b.client, 'Hello again @alice', { clientId: 'repeat-mention' });
  await post(b.client, 'Hello again @alice', { clientId: 'repeat-mention' });
  assert.equal((await notes(a.client, 'mention')).items.length, 1, 'retried posts notify once');
  assert.equal((await notes(a.client, 'mention')).items[0].targetPath, `/community/post/${mention.id}`);
  await post(a.client, 'Hello @alice');
  assert.equal((await notes(a.client, 'mention')).items.length, 1, 'no self notification');
  const edited = await post(b.client, 'No mention yet');
  await send(b.client, `/api/community/posts/${edited.id}`, { body: 'Now @alice' }, 'PATCH');
  await send(b.client, `/api/community/posts/${edited.id}`, { body: 'Still @alice' }, 'PATCH');
  assert.equal((await notes(a.client, 'mention')).items.length, 2, 'new tags on edit notify once');

  const thread = await post(b.client, 'Discussion');
  await post(a.client, 'I joined', { parentId: thread.id });
  const reply = await post(c.client, 'Another comment', { parentId: thread.id });
  assert.equal((await notes(a.client, 'comment')).items[0].postId, reply.id);
  assert.equal((await notes(b.client, 'reply')).items.length, 2);
  await prefs(a.client, { comments: false });
  await post(c.client, 'Muted discussion', { parentId: thread.id });
  assert.equal((await notes(a.client, 'comment')).items.length, 1);
  await send(a.client, '/api/community/profiles/bob/follow', {});
  const followed = await post(b.client, 'For my followers');
  assert.equal((await notes(a.client, 'following_post')).items[0].postId, followed.id);
  await prefs(a.client, { following: false });
  await post(b.client, 'Quiet post');
  assert.equal((await notes(a.client, 'following_post')).items.length, 1);
  await send(a.client, '/api/community/profiles/carol/block', {});
  await post(c.client, 'Blocked @alice');
  assert.equal((await notes(a.client, 'mention')).items.length, 2, 'blocks suppress mentions');
  await prefs(d.client, { enabled: false });
  await post(b.client, 'Disabled @dave');
  assert.equal((await notes(d.client)).items.length, 0);

  await prefs(a.client, { newsletters: false, comments: true });
  const newsletter = await root.collection('newsletters').create({ title: 'Notification test issue', status: 'draft', commentItems: [] });
  assert.equal((await notes(b.client, 'newsletter')).items.length, 0);
  await root.collection('newsletters').update(newsletter.id, { status: 'published' });
  assert.equal((await notes(b.client, 'newsletter')).items.length, 1);
  assert.equal((await notes(a.client, 'newsletter')).items.length, 0);
  assert.equal((await notes(d.client, 'newsletter')).items.length, 0);
  await root.collection('newsletters').update(newsletter.id, { title: 'Updated title' });
  await root.collection('newsletters').update(newsletter.id, { status: 'draft' });
  await root.collection('newsletters').update(newsletter.id, { status: 'published' });
  await tick();
  assert.equal((await notes(b.client, 'newsletter')).items.length, 1, 'edits and republication do not repeat publication alerts');
  const commentA = { id: 'one', authorId: a.id, authorName: 'alice', body: 'Joined', createdAt: new Date().toISOString() };
  const commentB = { id: 'two', authorId: b.id, authorName: 'bob', body: 'New comment', createdAt: new Date().toISOString() };
  await root.collection('newsletters').update(newsletter.id, { commentItems: [commentA] });
  await root.collection('newsletters').update(newsletter.id, { commentItems: [commentB, commentA] });
  assert.equal((await notes(a.client, 'comment')).items.length, 2, 'newsletter participants receive comments too');
  await root.collection('newsletters').update(newsletter.id, { commentItems: [{ ...commentB, likes: 1 }, commentA] });
  assert.equal((await notes(a.client, 'comment')).items.length, 2);

  const start = Date.now() + 60 * 60000;
  const event = { id: 'event-one', title: 'Planning meeting', startDate: new Date(start).toISOString(), attendees: [{ userId: a.id }, { userId: b.id }, { userId: d.id }] };
  await prefs(b.client, { events: false });
  await root.collection('newsletters').update(newsletter.id, { event });
  await tick(start - 31 * 60000);
  assert.equal((await notes(a.client, 'event')).items.length, 0);
  await tick(start - 30 * 60000); await tick(start - 29 * 60000);
  assert.equal((await notes(a.client, 'event')).items.length, 1, 'reminder delivered once at 30 minutes');
  assert.equal((await notes(a.client, 'event')).items[0].targetPath, `/article/${newsletter.id}`);
  assert.equal((await notes(b.client, 'event')).items.length, 0);
  assert.equal((await notes(d.client, 'event')).items.length, 0);
  await root.collection('newsletters').update(newsletter.id, { event: { ...event, startDate: new Date(start + 3600000).toISOString(), attendees: [{ userId: c.id }] } });
  await tick(start + 30 * 60000);
  assert.equal((await notes(a.client, 'event')).items.length, 1, 'canceled RSVP gets no rescheduled reminder');
  assert.equal((await notes(c.client, 'event')).items.length, 1, 'rescheduled event reminds current attendees');
  await tick(start + 3 * 3600000);
  assert.equal((await notes(c.client, 'event')).items.length, 1, 'expired events do not notify');
  const jobsBefore = (await root.collection('notification_jobs').getList(1, 1)).totalItems;
  await assert.rejects(send(root, '/api/test/notifications/rollback', {}), (error) => error.status === 400);
  assert.equal((await root.collection('notification_jobs').getList(1, 1)).totalItems, jobsBefore, 'rolled-back content leaves no notification job');

  const aInbox = await notes(a.client);
  const firstId = aInbox.items[0].id;
  await send(b.client, '/api/community/notifications/read', { ids: [firstId] });
  assert.equal((await root.collection('community_notifications').getOne(firstId)).isRead, false, 'cannot mark another user\'s alert');
  await send(a.client, '/api/community/notifications/read', { ids: [firstId] });
  assert.equal((await get(a.client, '/api/notifications/unread')).unreadCount, aInbox.unreadCount - 1);
  for (let i = 0; i < 505; i++) await root.collection('community_notifications').create({ userId: a.id, actorId: b.id, kind: 'mention', postId: `bulk-${i}` });
  const seen = new Set(); let cursor = '';
  do {
    const page = await get(a.client, '/api/community/notifications?perPage=50' + (cursor ? '&cursor=' + encodeURIComponent(cursor) : ''));
    for (const item of page.items) { assert.ok(!seen.has(item.id)); seen.add(item.id); }
    cursor = page.hasMore ? page.cursor : '';
  } while (cursor);
  assert.equal(seen.size, aInbox.items.length + 505);
  await send(a.client, '/api/community/notifications/read', { ids: [] });
  assert.equal((await get(a.client, '/api/notifications/unread')).unreadCount, 0, 'mark all handles more than 500 notifications');
  for (const collection of ['notification_preferences', 'notification_jobs', 'community_notifications']) {
    await assert.rejects(a.client.collection(collection).create({ userId: b.id }), (error) => [400, 403].includes(error.status));
    await assert.rejects(a.client.collection(collection).getList(1, 1), (error) => error.status === 403, 'private records are not readable through collection API');
  }
  const browserStart = await get(b.client, '/api/notifications/browser?locale=en');
  assert.equal(browserStart.items.length, 0, 'enabling pop-ups does not replay old notifications');
  const browserPost = await post(a.client, 'Browser alert @bob');
  const browserNext = await get(b.client, '/api/notifications/browser?locale=en&cursor=' + encodeURIComponent(browserStart.cursor));
  assert.equal(browserNext.items.length, 1);
  assert.equal(browserNext.items[0].path, `/community/post/${browserPost.id}`);
  assert.equal((await get(b.client, '/api/notifications/browser?cursor=' + encodeURIComponent(browserNext.cursor))).items.length, 0);
  await assert.rejects(send(b.client, '/api/community/notifications/read', { ids: 'invalid' }), (error) => error.status === 400);

  const config = await get(b.client, '/api/notifications/push/config');
  assert.deepEqual(Object.keys(config), ['publicKey'], 'private signing key never leaves the server');
  assert.match(config.publicKey, /^[\w-]{87}$/);
  assert.deepEqual(await get(b.client, '/api/notifications/push/config'), config, 'signing key persists');
  const subscription = { endpoint: 'https://fcm.googleapis.com/fcm/send/disposable-notification-test', keys: { p256dh: config.publicKey, auth: Buffer.alloc(16, 5).toString('base64url') } };
  const subscribe = (client, value = subscription) => send(client, '/api/notifications/push/subscribe', { subscription: value, locale: 'en' });
  await assert.rejects(subscribe(anonymous), (error) => error.status === 401);
  for (const endpoint of ['http://127.0.0.1:8090/private', 'https://fcm.googleapis.com.evil.example/push', 'https://user:pass@fcm.googleapis.com/push']) await assert.rejects(subscribe(b.client, { ...subscription, endpoint }), (error) => error.status === 400);
  await subscribe(b.client); await subscribe(b.client);
  assert.equal((await root.collection('notification_push_subscriptions').getList(1, 20)).totalItems, 1, 'registering the same browser is idempotent');
  await assert.rejects(subscribe(c.client, { ...subscription, keys: { ...subscription.keys, auth: Buffer.alloc(16, 6).toString('base64url') } }), (error) => error.status === 403);
  await send(c.client, '/api/notifications/push/unsubscribe', { endpoint: subscription.endpoint });
  assert.equal((await root.collection('notification_push_subscriptions').getList(1, 20)).totalItems, 1, 'one user cannot remove another browser');
  await post(a.client, 'Background alert @bob');
  let pushJobs = await root.collection('notification_push_jobs').getFullList();
  assert.equal(pushJobs.length, 1, 'closed-site delivery is enabled by default');
  await send(root, '/api/test/notifications/push', { status: 503 });
  let pushJob = await root.collection('notification_push_jobs').getOne(pushJobs[0].id);
  assert.equal(pushJob.completed, false); assert.equal(pushJob.attempts, 1);
  assert.ok(Date.parse(pushJob.nextAttemptAt) > Date.now(), 'transient failures back off');
  await root.collection('notification_push_jobs').update(pushJob.id, { nextAttemptAt: '2000-01-01T00:00:00.000Z' });
  await send(root, '/api/test/notifications/push', { status: 201 });
  assert.equal((await root.collection('notification_push_jobs').getOne(pushJob.id)).completed, true);
  await prefs(b.client, { background: false });
  const openStart = await get(b.client, '/api/notifications/browser');
  await post(a.client, 'Open-site-only alert @bob');
  assert.equal((await root.collection('notification_push_jobs').getFullList()).length, 1, 'open-site-only mode does not enqueue Web Push');
  assert.equal((await get(b.client, '/api/notifications/browser?cursor=' + encodeURIComponent(openStart.cursor))).items.length, 1, 'open-site mode receives new pop-ups through the browser feed');
  await prefs(b.client, { background: true });
  await post(a.client, 'Expired subscription @bob');
  await send(root, '/api/test/notifications/push', { status: 410 });
  assert.equal((await root.collection('notification_push_subscriptions').getList(1, 20)).totalItems, 0, 'expired browser subscriptions are removed');
  await subscribe(b.client);
  await post(a.client, 'Preference changed before sending @bob');
  await prefs(b.client, { browser: false });
  await send(root, '/api/test/notifications/push', { status: 201 });
  pushJobs = await root.collection('notification_push_jobs').getFullList();
  assert.equal(pushJobs.find((job) => job.attempts === 0)?.completed, true, 'preferences are checked again before sending');
  await send(b.client, '/api/notifications/push/unsubscribe', { endpoint: subscription.endpoint });
  await prefs(b.client, { browser: true });
  console.log('Passed: browser pop-up modes, public key configuration, private subscriptions, SSRF rejection, delivery retries, expired subscriptions, deduplication and preference changes before delivery.');
  console.log('Passed: notification preferences, auth isolation, mentions and edits, thread participation, follows, blocks, global disable, newsletters, comments, timed/rescheduled/canceled events, transaction rollback, duplicate suppression, pagination and marking 500+ alerts read.');
} catch (error) {
  console.error(error.message, error.response || '', error.stack?.split('\n').filter((line) => !line.includes('pocketbase.es.mjs')).slice(0, 5).join('\n'));
  process.exitCode = 1;
} finally {
  if (!process.env.NOTIFICATION_TEST_KEEP_SERVER) server.kill();
  await writeFile(path.join(directory, 'server.log'), logs);
  console.log(`Disposable test data: ${directory}`);
}
